/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cleaninginventory.cleaninginventory;

/**
 *
 * @author roebssie
 */
public class InventoryIssuanceFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventoryIssuanceFrame.class.getName());

    /**
     * Creates new form InventoryIssuanceFrame
     */
   public InventoryIssuanceFrame() {
        initComponents();
        loadItemsIntoComboBox(); // Load database items when the frame starts
        // Force the text fields to be a normal size (Width: 150 pixels, Height: 26 pixels)
       // Force the layout sizes securely
       // 1. Give them some default blank space so the layout manager stops squishing them
       // 1. Give them some default blank space so the layout manager stops squishing them
        txtQuantity.setText("      "); 
        txtIssuedTo.setText("                    ");
        
        // 2. Force the sizes securely
        java.awt.Dimension fieldSize = new java.awt.Dimension(150, 26);
        
        txtQuantity.setPreferredSize(fieldSize);
        txtQuantity.setMinimumSize(fieldSize);
        txtQuantity.setSize(fieldSize);
        
        txtIssuedTo.setPreferredSize(fieldSize);
        txtIssuedTo.setMinimumSize(fieldSize);
        txtIssuedTo.setSize(fieldSize);
        
        // 3. Force the frame to recalculate based on the new content
        this.invalidate();
        this.validate();
        this.pack();
    }

    private void loadItemsIntoComboBox() {
        // Clear default NetBeans placeholder values like "Item 1"
        cmbItems.removeAllItems();
        
        // Use your existing DAO to fetch items
        cleaninginventory.cleaninginventory.dao.InventoryItemDAO itemDAO = new cleaninginventory.cleaninginventory.dao.InventoryItemDAO();
        java.util.List<cleaninginventory.cleaninginventory.models.InventoryItem> items = itemDAO.getAllInventoryItems();
        
        // Loop through the items and add their names to the dropdown
        for (cleaninginventory.cleaninginventory.models.InventoryItem item : items) {
            cmbItems.addItem(item.getItemName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbItems = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIssuedTo = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Issue Cleaning Materials");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 6, -1, -1));

        jLabel2.setText("Select Item:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 70, -1, -1));

        cmbItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 67, -1, -1));

        jLabel3.setText("Quantity:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 111, -1, -1));

        txtQuantity.setColumns(20);
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 108, -1, -1));

        jLabel4.setText("Issued To (Staff Name):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 152, -1, -1));

        txtIssuedTo.setColumns(20);
        getContentPane().add(txtIssuedTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 149, -1, -1));

        btnConfirm.setText("Confirm Issuance");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 227, -1, -1));

        btnBack.setText("Back to Dashboard");
        btnBack.addActionListener(this::btnBackActionPerformed);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 227, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new DashboardFrame().setVisible(true); // Re-open the main dashboard
        this.dispose(); // Close this issuance frame
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        String selectedItemName = (String) cmbItems.getSelectedItem();
        String quantityStr = txtQuantity.getText().trim();
        String issuedTo = txtIssuedTo.getText().trim();
        
        // 1. Validation checks
        if (selectedItemName == null || quantityStr.isEmpty() || issuedTo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int qtyToIssue = Integer.parseInt(quantityStr);
            if (qtyToIssue <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // 2. Find the full item object to get its ID and current stock level
            cleaninginventory.cleaninginventory.dao.InventoryItemDAO itemDAO = new cleaninginventory.cleaninginventory.dao.InventoryItemDAO();
            java.util.List<cleaninginventory.cleaninginventory.models.InventoryItem> items = itemDAO.getAllInventoryItems();
            cleaninginventory.cleaninginventory.models.InventoryItem targetItem = null;
            
            for (cleaninginventory.cleaninginventory.models.InventoryItem item : items) {
                if (item.getItemName().equals(selectedItemName)) {
                    targetItem = item;
                    break;
                }
            }
            
            if (targetItem != null) {
                // 3. Check if there's enough stock available
                if (targetItem.getQuantityAvailable() < qtyToIssue) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "Insufficient stock! Available: " + targetItem.getQuantityAvailable(), 
                        "Stock Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                // 4. Update the database stock level
                int newQuantity = targetItem.getQuantityAvailable() - qtyToIssue;
                boolean updated = itemDAO.updateStockQuantity(targetItem.getItemId(), newQuantity);
                
if (updated) {
            // Success message
            javax.swing.JOptionPane.showMessageDialog(this,
                qtyToIssue + " units of " + selectedItemName + " successfully issued to " + issuedTo + "!",
                "Issuance Successful", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // 🚨 ADD THE LOW STOCK CHECK HERE:
          if (newQuantity <= targetItem.getMinimumStockLevel()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "⚠️ LOW STOCK WARNING!\n" + selectedItemName + " is now at " + newQuantity +
                    " units.\nMinimum required level is " + targetItem.getMinimumStockLevel() + ".",
                    "Restock Required", javax.swing.JOptionPane.WARNING_MESSAGE);
            }

            // Clear fields for the next input
            txtQuantity.setText("");
            txtIssuedTo.setText("");
        } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to update stock in database.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for quantity.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InventoryIssuanceFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cmbItems;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtIssuedTo;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
